# Data Processor Development Configuration
spring:
  application:
    name: data-processor

  # Database Configuration (shared with back-end dev)
  datasource:
    url: jdbc:mysql://172.23.207.87:3306/gest-form?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: hello!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Let back-end manage the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  sql:
    init:
      mode: always
      platform: mysql

  # Liquibase Configuration - DISABLED (back-end manages schema)
  liquibase:
    enabled: false

# Enhanced Logging for Development
logging:
  level:
    "[com.example.dataprocessor]": DEBUG
    "[com.example.demo]": INFO
    "[org.springframework]": INFO
    "[org.hibernate.SQL]": DEBUG

# Development specific settings
server:
  port: 8083

# Custom application properties
app:
  json:
    input-folder: ../batch-processor/output
    processed-folder: processed
    error-folder: error
  processing:
    chunk-size: 50 # Smaller chunks for dev testing
    max-retry-attempts: 3
    # Staging data processing configuration
    enabled: true
    interval: 60000 # 1 minute for dev testing
