spring:
  application:
    name: data-processor

  # Connect to main MySQL database (same as back-end)
  datasource:
    url: jdbc:mysql://172.23.207.87:3306/gest-form?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: hello!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Let Liquibase handle the schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always
      platform: mysql

  # Liquibase Configuration - DISABLED (back-end manages schema)
  liquibase:
    enabled: false

# Server Configuration
server:
  port: 8083

# Enhanced Logging for Development
logging:
  level:
    liquibase: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.example.dataprocessor: DEBUG
    org.springframework.web: DEBUG
    web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,liquibase

# Custom application properties
app:
  json:
    input-folder: ../batch-processor/output
    processed-folder: processed
    error-folder: error
  processing:
    chunk-size: 100
    max-retry-attempts: 3
    enable-scheduler: true
    scheduler-interval: 30000 # Check every 30 seconds
