spring:
  application:
    name: batch-processor

  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false # Disable automatic job execution on startup
    jdbc:
      initialize-schema: always

server:
  port: 8081

logging:
  level:
    com.example.batchprocessor: DEBUG
    org.springframework.batch: INFO
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom application properties
app:
  csv:
    input-folder: input
    processed-folder: processed
    error-folder: error
