# Fixed MySQL Configuration for Liquibase
spring:
  application:
    name: gestionale-formazione

  sql:
    init:
      mode: always
      platform: mysql

  # MySQL Database Configuration (FIXED)
  datasource:
    url: jdbc:mysql://localhost:3307/gest-form?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Agostino96!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # ✅ FIXED: Let Liquibase handle schema creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  # Fixed Liquibase Configuration for MySQL
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: gest-form # ✅ FIXED: Use actual MySQL database name
    # Alternative: remove default-schema entirely to use connection default

# Security Configuration
sicurezza:
  uri: /auth
  refresh: /refresh
  header: Authorization
  prefix: Bearer
  expiration: 600
  secret: wNoe5AlDAtrrRJtbPQZ6UtdgvYwF2DKYSlNEVcCD/IzToqX9bXpmRzflYBGDViZDJgV3HTPfDGY5ix1U9hJtfA==

# Enhanced Logging for Debugging
logging:
  level:
    liquibase: DEBUG # See what Liquibase is trying to do
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
